name: Validate
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm types:check
      - run: pnpm test
      - run: pnpm build
